package:
  name: fwdpy11
  version: "0.14.1"

source:
  url: https://files.pythonhosted.org/packages/73/45/1b7712ff3b2a35abd5d6eb312c3ec4ece537b3b9e9f2d9cd5f39d68be2aa/fwdpy11-0.14.1.tar.gz
  sha256: 3cf7058efc17f6dbccfcb8b21590a7bdefbfbf5804d069b63dc218a6d632080a

build:
  skip: True # [py27]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - pkgconfig
    - python
    - pip
    - numpy >=1.10
    - pybind11 >=2.6.0
    - tskit >=0.3.2
    - gsl
    - openblas
    - attrs
    - setuptools_scm
  run:
    - python
    - numpy >=1.10
    - tskit >=0.3.2
    - gsl
    - openblas
    - sparse
    - attrs
    - black

test:
  # Python imports
  imports:
    - fwdpy11

about:
  home: http://pypi.python.org/pypi/fwdpy11
  license: GNU General Public License v3 or later (GPLv3+)
  summary: 'Forward-time population genetic simulation in Python.'

extras:
  identifiers:
    - 10.1534/genetics.114.165019
    - 10.1371/journal.pcbi.1006581
