{% set name = "toulligqc" %}
{% set version = "2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e363ecd1d85d88d6b8441ffe75f74253dc75f767bc06dc111bcf75c999b4ec74

build:
  number: 0
  entry_points:
    - toulligqc=toulligqc.toulligqc:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "
  noarch: python

requirements:
  host:
    - pip
    - python >=3
  run:
    - h5py >=2.7,<2.8
    - matplotlib >=2.1,<2.2
    - numpy >=1.13,<1.14
    - pandas >=0.22,<0.23
    - plotly >=2.2,<2.3
    - python >=3
    - seaborn >=0.8,<0.9

test:
  imports:
    - toulligqc
  commands:
    - toulligqc --help

about:
  home: https://github.com/GenomicParisCentre/toulligQC
  license: GPL-3.0
  license_family: GPL
  summary: A post sequencing QC tool for Oxford Nanopore sequencers
